apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: otel-collector-podmonitor
  namespace: monitoring
  labels:
    release: prometheous-grafana
spec:
  podMetricsEndpoints:
  - port: prometheus
  selector:
    matchLabels:
      app.kubernetes.io/instance: otel-collector
      app.kubernetes.io/name: opentelemetry-collector
