project: bank-demo
service: customer-service
namespace: bank-demo

replicas: 1
port: 8080

image:
  repository: bunnana/bank-demo/customer-service
  tag: "0.0.7-4"
  pullPolicy: Never

java:
  spring:
    enabled: true

vault:
  dynamicSecrets:
  - name: db-creds
    mount: database
    path: static-creds/bank-demo-customer-service

env:
- name: POSTGRES_USER
  secretName: db-creds
  secretKey: username
- name: POSTGRES_PASSWORD
  secretName: db-creds
  secretKey: password

ingress:
  enabled: true
  hosts:
  - host: bank-demo.bunnana.dev
    tlsSecretName: bank-demo-cert-tls
    paths:
    - path: /customer-service
      pathType: Prefix
