project: bank-demo
service: customer-service
namespace: bank-demo

replicas: 1
port: 8080

image:
  repository: bunnana/bank-demo/customer-service
  tag: "0.0.7-1"
  pullPolicy: Never

vault:
  dynamicSecrets:
  - name: db-creds
    mount: database
    path: static-creds/bank-demo-customer-service

env:
- name: MANAGEMENT_OTLP_TRACING_ENDPOINT
  value: http://otel-collector-opentelemetry-collector.monitoring.svc:4317
- name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
  value: "1.0"
- name: LOGGING_LEVEL_IO_OPENTELEMETRY
  value: DEBUG
- name: DEBUG
  value: "true"
- name: POSTGRES_HOST
  value: postgres-postgresql.postgres.svc:5432
- name: POSTGRES_DB
  value: bank_demo_customer_db
- name: POSTGRES_USER
  secretName: db-creds
  secretKey: username
- name: POSTGRES_PASSWORD
  secretName: db-creds
  secretKey: password
- name: JWT_JWK_SET_URI
  value: http://customer-service:8080/customer-service/.well-known/jwks.json
- name: VAULT_URI
  value: http://vault.vault.svc:8200
- name: VAULT_KUBERNETES_ROLE
  value: bank-demo-customer-service-vso
- name: NODE_NAME
  fieldPath: spec.nodeName
- name: POD_NAMESPACE
  fieldPath: metadata.namespace

ingress:
  enabled: true
  hosts:
  - host: bank-demo.bunnana.dev
    tlsSecretName: bank-demo-cert-tls
    paths:
    - path: /customer-service
      pathType: Prefix
