apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: prometheous-grafana-grafana-admin
  namespace: monitoring
spec:
  vaultAuthRef: prometheous-grafana-vault-auth
  type: kv-v2
  mount: secret
  path: grafana
  refreshAfter: 1h
  destination:
    name: prometheous-grafana-grafana-admin
    create: true
