apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bunnanna/kube-argo.git
      revision: main
      files:
      - path: "common/*/helm.yaml"
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      sources:
      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          valueFiles:
          - $values/{{.path.path}}/values.yaml
      - repoURL: https://github.com/bunnanna/kube-argo.git
        targetRevision: main
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true