apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-apply-install
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/bunnanna/kube-argo.git
      revision: main
      files:
      - path: "common/*/install/kustomization.yaml"
  - git:
      repoURL: https://github.com/bunnanna/kube-argo.git
      revision: main
      files:
      - path: "common/*/install/helm.yaml"
  template:
    metadata:
      name: '{{index .path.segments 1}}'
    spec:
      project: default
      sources:
      {{- if .chart }}
      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          valueFiles:
          - $values/{{.path.path}}/values.yaml
      - repoURL: https://github.com/bunnanna/kube-argo.git
        targetRevision: main
        ref: values
      {{- else }}
      - repoURL: https://github.com/bunnanna/kube-argo.git
        targetRevision: main
        path: '{{.path.path}}'
      {{- end }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
