apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bunnanna/kube-argo.git
    targetRevision: main
    path: common/argocd/install
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true