apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: issue-cert
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bunnanna/kube-argo.git
      revision: main
      files:
      - path: "common/cert-manager/cert/*.yaml"
  template:
    metadata:
      name: '{{.metadata.name}}'
    spec:
      project: default
      sources:
      - repoURL: https://github.com/bunnanna/kube-argo.git
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.metadata.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true