apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "service.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "service.fullname" . }}
    spec:
      serviceAccountName: {{ include "service.fullname" . }}-vso
      containers:
        - name: {{ .Values.service }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          env:
          {{- range .Values.env }}
            - name: {{ .name }}
              {{- if hasKey . "value" }}
              value: {{ .value | quote }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "service.fullname" $ }}-{{ .secretName }}
                  key: {{ .secretKey }}
              {{- end }}
          {{- end }}
