{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service.name" . }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: kong
  tls:
  {{- range .Values.ingress.hosts }}
  - hosts:
    - {{ .host }}
    secretName: {{ .tlsSecretName }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ include "service.name" $ }}
            port:
              number: {{ $.Values.port }}
      {{- end }}
  {{- end }}
{{- end }}
