apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "service.name" . }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
