{{- range .Values.vault.kvSecrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "service.fullname" $ }}-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  vaultAuthRef: {{ include "service.fullname" $ }}-vault-auth
  type: {{ .version | default "kv-v2" }}
  mount: {{ .mount }}
  path: {{ .path }}
  refreshAfter: {{ .refreshAfter | default "1h" }}
  destination:
    name: {{ include "service.fullname" $ }}-{{ .name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "service.fullname" $ }}
{{- end }}
