{{- range .Values.vault.secrets }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "service.fullname" $ }}-{{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  mount: {{ .mount }}
  path: {{ .path }}
  refreshAfter: {{ $.Values.vault.refreshAfter }}
  destination:
    name: {{ include "service.fullname" $ }}-{{ .name }}
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "service.fullname" $ }}
{{- end }}
