apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "service.fullname" . }}-db-creds
  namespace: {{ .Values.namespace }}
spec:
  mount: database
  path: static-creds/{{ include "service.fullname" . }}
  refreshAfter: {{ .Values.vault.refreshAfter }}
  destination:
    name: {{ include "service.fullname" . }}-db-creds
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "service.fullname" . }}
