grafana:
  admin:
    existingSecret: prometheous-grafana-grafana-admin
    userKey: admin_user
    passwordKey: admin_password
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
    - name: Tempo
      type: tempo
      url: http://tempo:3100
      access: proxy
      isDefault: false


prometheus:
  prometheusSpec:
    retention: 1d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

alertmanager:
  enabled: false